import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './component/Header';
import { getServerSession } from "next-auth";
import LoginBtn from "./component/LoginBtn";
import LogOutBtn from "./component/LogOutBtn";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Link from "next/link";
import { cookies } from "next/headers";
import DarkMode from "./component/darkmode";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  let session = await getServerSession(authOptions);

  let cookie = cookies().get("uimode");
  //console.log(cookie);

  return (
    <html lang="en">
      <body className={cookie?.value == 'dark' ? 'dark-mode' : 'light-mode'} >
        <Header />
        {
          session && session.user ? <span>{session.user.name} <LogOutBtn/> </span>
          :  <span> <LoginBtn /> <Link className="button" href={`/register`}>회원가입</Link> </span>
        }
        <DarkMode />
        {children}
      </body>
    </html>
  );
}
