import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from './component/Header';
import { getServerSession } from "next-auth";
import LoginBtn from "./component/LoginBtn";
import LogOutBtn from "./component/LogOutBtn";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  let session = await getServerSession(authOptions);

  
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        {
          session && session.user ? <span>{session.user.name} <LogOutBtn/> </span>
          :  <span> <LoginBtn /> <Link className="button" href={`/register`}>회원가입</Link> </span>
        }
        {children}
      </body>
    </html>
  );
}
